main: main.c
#	@echo "-g: GDB Debug flag enabled"
#	@echo "-z execstack: DEP disabled"
#	@echo "-fno-stack-protector: Stack smashing protection disabled"
#	@echo 
	gcc-5 -m32 -g -z execstack -fno-stack-protector -o main main.c